version: '2'
services:
  suggestionsbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_API=${DISCORD_API}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    volumes:
      - type: bind
        source: /data/bot_registry
        target: /data/bot_registry
    image: suggestionsbot
