version: '2'
services:
  suggestionsbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DISCORD_API=${DISCORD_API}
        - COMMAND_PREFIX=${COMMAND_PREFIX}
    image: suggestionsbot
