name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

environment: staging_environment

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build and run latest code
        env:
          DISCORD_API: ${{ secrets.DISCORD_API }}
          COMMAND_PREFIX: ${{ secrets.COMMAND_PREFIX }}
        run: docker-compose up --build -d

      - name: Remove old unused images
        run: docker image prune -f

      - name: Remove old unused containers
        run: docker container prune -f
