name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build and run latest code
        run: docker-compose up --build -d

      - name: Remove old unused images
        run: docker image prune -f

      - name: Remove old unused containers
        run: docker container prune -f
